from browser import document
from random import choice


"""
# A class that, given a list of Subtitles, will, given the date and time,
# choose an appropriate one randomly.
class SubtitleGenerator:

    def __init__(self, subtitles):
        self.subtitles = subtitles

    def getSubtitle(self):
        return choice(self.subtitles)
"""

subtitles = [
    'Mysticism is the odd child of totalitarianism and nihilism.',
    'Giving a kid medication when they’re young is like making a person out of tape and glue.',
    'Don’t forget to be curious!!!',
    '"When you plant an olive tree, it is always a selfless act, because you won’t be alive to see it bear fruit."',
    'Let your heartbeat come from everywhere in your body. Relax.',
    'Humility never goes out of style.',
    'I can’t make a single metaphor without thinking about what metaphors are.',
    'Wow. I can create meaning.',
    'Get all the passengers on a plane to jump so that the plane wobbles.',
    'Math systems generated by different axioms are dialects of the immortal language.',
    'Take some more time to clarify your objectives.',
    'Maybe I will never be possessed.',
    '“Sufficient unto the day is the evil thereof.”',
    '"And ye shall eat bread..."',
    'Pain is as objective as subjective gets.',
    'Once you stop expecting anything, you know that you can trust yourself.',
    'Phædrus’s knife is the unifying element between bureaucracy and program design!',
    'Yes, you can fit some good work into half an hour. Don’t be afraid to get started!',
    'I miss long car rides with nothing to do.',
    'Porn is to sex as social media is to conversation.',
    'Attempting to dig on the wrong side of the gravestone.',
    '“Salmon is delicious and easily digestible.”',
    'Consumerism: because misery loves companies.',
    'Association of Secular Students: a 501(c)(3) Non-Prophet.',
    '“Anxiety is the dizziness of freedom.”',
    '"You are not your thoughts."',
    'I am more interested in studying Nature than I am in studying things people have made.',
    'Nothing feels like travel quite like sweaty jeans.',
    'What would it be like to live in a noticeably hyperbolic universe?',
    '"She spoke conclusory noises to the telephone, then set it down."',
    'Did I actually just think about X? ...Of course I did, otherwise I wouldn’t be thinking about this!',
    'Humanity is in a prison of its own inability.',
    'We are always insufficient.',
    'Every thought pattern is a skill that can be refined — it\'s just a neural net cost function, after all.',
    'What if aliens only experimented on people when they were high?',
    'People are more interesting when they’re alone.',
    'More intelligent beings would see so much more beauty in reality.',
    'Uncertainty in life breeds intelligence, certainty breeds an interest in it.',
    'Hey. I make annoying noises. It’s part of who I am. I love the repetitiveness. It’s satisfying.',
    'The. Bronze. Age. Collapse.',
    '“I’m not sure about all this, but I’m not sure how to phrase my distrust.”',
    '“Mathematical objects and concepts are as objective as physical objects and properties.”',
    'What if human behavior can be modeled on the computational complexity of the problem they’re trying to solve?',
    'Just write the story itself, not everything else around it.',
    'Don’t be afraid to live life like a story. Be weird.',
    'I’m, like, the formula pimp.',
    'A civilization means they build buildings there.',
    'Why do we consider thoughts to be individual things? What is a thought?',
    'Look around! You can see math everywhere.',
    'Languages evolve like creatures. Their capacity for description grows and evolves overtime to suit environments.',
]

try:
    document["subtitle"] <= choice(subtitles)
except:
    document["subtitle"] <= "Well, at least we get this far."

